# Generated by Django 5.2.4 on 2025-07-12 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_projectfile_project_files'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['name', 'id']},
        ),
    ]
